/** Home county first, then adjacent counties. Key is "City|State". */
const NEARBY: Record<string, string[]> = {
  "Birmingham|Alabama": ["Jefferson", "Shelby", "St. Clair", "Blount", "Walker"],
  "Huntsville|Alabama": ["Madison", "Limestone", "Morgan", "Marshall"],
  "Montgomery|Alabama": ["Montgomery", "Elmore", "Autauga", "Lowndes"],
  "Mobile|Alabama": ["Mobile", "Baldwin"],
  "Tuscaloosa|Alabama": ["Tuscaloosa", "Hale", "Bibb", "Jefferson"],
  "Anchorage|Alaska": ["Anchorage", "Matanuska-Susitna", "Kenai Peninsula"],
  "Fairbanks|Alaska": ["Fairbanks North Star", "Denali"],
  "Juneau|Alaska": ["Juneau"],
  "Wasilla|Alaska": ["Matanuska-Susitna", "Anchorage"],
  "Sitka|Alaska": ["Sitka"],
  "Phoenix|Arizona": ["Maricopa", "Pinal"],
  "Tucson|Arizona": ["Pima", "Pinal", "Santa Cruz"],
  "Mesa|Arizona": ["Maricopa", "Pinal"],
  "Chandler|Arizona": ["Maricopa", "Pinal"],
  "Gilbert|Arizona": ["Maricopa", "Pinal"],
  "Little Rock|Arkansas": ["Pulaski", "Saline", "Lonoke", "Faulkner"],
  "Fort Smith|Arkansas": ["Sebastian", "Crawford"],
  "Fayetteville|Arkansas": ["Washington", "Benton"],
  "Springdale|Arkansas": ["Washington", "Benton"],
  "Jonesboro|Arkansas": ["Craighead", "Poinsett"],
  "Los Angeles|California": ["Los Angeles", "Orange", "Ventura", "San Bernardino"],
  "San Diego|California": ["San Diego", "Orange", "Imperial"],
  "San Jose|California": ["Santa Clara", "Alameda", "San Mateo"],
  "San Francisco|California": ["San Francisco", "San Mateo", "Marin", "Alameda"],
  "Fresno|California": ["Fresno", "Madera", "Kings"],
  "Denver|Colorado": ["Denver", "Arapahoe", "Adams", "Jefferson"],
  "Colorado Springs|Colorado": ["El Paso", "Teller", "Pueblo"],
  "Aurora|Colorado": ["Arapahoe", "Adams", "Douglas"],
  "Fort Collins|Colorado": ["Larimer", "Weld"],
  "Lakewood|Colorado": ["Jefferson", "Denver"],
  "Bridgeport|Connecticut": ["Fairfield", "New Haven"],
  "Stamford|Connecticut": ["Fairfield"],
  "New Haven|Connecticut": ["New Haven", "Middlesex"],
  "Hartford|Connecticut": ["Hartford", "Middlesex", "Tolland"],
  "Waterbury|Connecticut": ["New Haven", "Litchfield"],
  "Wilmington|Delaware": ["New Castle"],
  "Dover|Delaware": ["Kent"],
  "Newark|Delaware": ["New Castle"],
  "Middletown|Delaware": ["New Castle"],
  "Smyrna|Delaware": ["Kent", "New Castle"],
  "Washington|District of Columbia": ["District of Columbia", "Montgomery", "Prince George's", "Arlington", "Fairfax"],
  "Jacksonville|Florida": ["Duval", "St. Johns", "Clay", "Nassau"],
  "Miami|Florida": ["Miami-Dade", "Broward"],
  "Tampa|Florida": ["Hillsborough", "Pinellas", "Pasco"],
  "Orlando|Florida": ["Orange", "Seminole", "Osceola", "Lake"],
  "St. Petersburg|Florida": ["Pinellas", "Hillsborough"],
  "Atlanta|Georgia": ["Fulton", "DeKalb", "Cobb", "Gwinnett", "Clayton"],
  "Columbus|Georgia": ["Muscogee", "Harris"],
  "Augusta|Georgia": ["Richmond", "Columbia"],
  "Macon|Georgia": ["Bibb", "Houston", "Jones"],
  "Savannah|Georgia": ["Chatham", "Effingham", "Bryan"],
  "Honolulu|Hawaii": ["Honolulu"],
  "Pearl City|Hawaii": ["Honolulu"],
  "Hilo|Hawaii": ["Hawaii"],
  "Kailua|Hawaii": ["Honolulu"],
  "Kaneohe|Hawaii": ["Honolulu"],
  "Boise|Idaho": ["Ada", "Canyon"],
  "Meridian|Idaho": ["Ada", "Canyon"],
  "Nampa|Idaho": ["Canyon", "Ada"],
  "Idaho Falls|Idaho": ["Bonneville", "Bingham"],
  "Caldwell|Idaho": ["Canyon", "Ada"],
  "Chicago|Illinois": ["Cook", "DuPage", "Lake", "Will"],
  "Aurora|Illinois": ["Kane", "DuPage", "Kendall"],
  "Naperville|Illinois": ["DuPage", "Will"],
  "Joliet|Illinois": ["Will", "Kendall"],
  "Rockford|Illinois": ["Winnebago", "Boone"],
  "Indianapolis|Indiana": ["Marion", "Hamilton", "Hendricks", "Johnson"],
  "Fort Wayne|Indiana": ["Allen"],
  "Evansville|Indiana": ["Vanderburgh", "Warrick"],
  "South Bend|Indiana": ["St. Joseph", "Elkhart"],
  "Carmel|Indiana": ["Hamilton", "Marion"],
  "Des Moines|Iowa": ["Polk", "Dallas", "Warren"],
  "Cedar Rapids|Iowa": ["Linn"],
  "Davenport|Iowa": ["Scott"],
  "Sioux City|Iowa": ["Woodbury"],
  "Iowa City|Iowa": ["Johnson"],
  "Wichita|Kansas": ["Sedgwick", "Butler"],
  "Overland Park|Kansas": ["Johnson"],
  "Kansas City|Kansas": ["Wyandotte", "Johnson"],
  "Olathe|Kansas": ["Johnson"],
  "Topeka|Kansas": ["Shawnee"],
  "Louisville|Kentucky": ["Jefferson", "Oldham", "Bullitt"],
  "Lexington|Kentucky": ["Fayette", "Jessamine", "Scott"],
  "Bowling Green|Kentucky": ["Warren"],
  "Owensboro|Kentucky": ["Daviess"],
  "Covington|Kentucky": ["Kenton", "Campbell", "Boone"],
  "New Orleans|Louisiana": ["Orleans", "Jefferson", "St. Bernard", "St. Tammany"],
  "Baton Rouge|Louisiana": ["East Baton Rouge", "Ascension", "Livingston"],
  "Shreveport|Louisiana": ["Caddo", "Bossier"],
  "Lafayette|Louisiana": ["Lafayette"],
  "Lake Charles|Louisiana": ["Calcasieu"],
  "Portland|Maine": ["Cumberland", "York"],
  "Lewiston|Maine": ["Androscoggin"],
  "Bangor|Maine": ["Penobscot"],
  "South Portland|Maine": ["Cumberland"],
  "Auburn|Maine": ["Androscoggin"],
  "Baltimore|Maryland": ["Baltimore City", "Baltimore County", "Anne Arundel", "Howard"],
  "Frederick|Maryland": ["Frederick", "Montgomery", "Carroll"],
  "Gaithersburg|Maryland": ["Montgomery", "Frederick"],
  "Rockville|Maryland": ["Montgomery"],
  "Bowie|Maryland": ["Prince George's", "Anne Arundel"],
  "Boston|Massachusetts": ["Suffolk", "Middlesex", "Norfolk"],
  "Worcester|Massachusetts": ["Worcester"],
  "Springfield|Massachusetts": ["Hampden", "Hampshire"],
  "Cambridge|Massachusetts": ["Middlesex", "Suffolk"],
  "Lowell|Massachusetts": ["Middlesex"],
  "Detroit|Michigan": ["Wayne", "Oakland", "Macomb"],
  "Grand Rapids|Michigan": ["Kent", "Ottawa"],
  "Warren|Michigan": ["Macomb", "Oakland"],
  "Sterling Heights|Michigan": ["Macomb", "Oakland"],
  "Ann Arbor|Michigan": ["Washtenaw", "Wayne"],
  "Minneapolis|Minnesota": ["Hennepin", "Ramsey", "Anoka"],
  "St. Paul|Minnesota": ["Ramsey", "Washington", "Dakota"],
  "Rochester|Minnesota": ["Olmsted"],
  "Bloomington|Minnesota": ["Hennepin", "Dakota"],
  "Duluth|Minnesota": ["St. Louis", "Carlton"],
  "Jackson|Mississippi": ["Hinds", "Rankin", "Madison"],
  "Gulfport|Mississippi": ["Harrison", "Hancock"],
  "Southaven|Mississippi": ["DeSoto"],
  "Hattiesburg|Mississippi": ["Forrest", "Lamar"],
  "Biloxi|Mississippi": ["Harrison"],
  "Kansas City|Missouri": ["Jackson", "Clay", "Platte", "Cass"],
  "St. Louis|Missouri": ["St. Louis City", "St. Louis County", "St. Charles"],
  "Springfield|Missouri": ["Greene", "Christian"],
  "Columbia|Missouri": ["Boone"],
  "Independence|Missouri": ["Jackson", "Clay"],
  "Billings|Montana": ["Yellowstone"],
  "Missoula|Montana": ["Missoula"],
  "Great Falls|Montana": ["Cascade"],
  "Bozeman|Montana": ["Gallatin"],
  "Butte|Montana": ["Silver Bow", "Jefferson"],
  "Omaha|Nebraska": ["Douglas", "Sarpy"],
  "Lincoln|Nebraska": ["Lancaster"],
  "Bellevue|Nebraska": ["Sarpy", "Douglas"],
  "Grand Island|Nebraska": ["Hall"],
  "Kearney|Nebraska": ["Buffalo"],
  "Las Vegas|Nevada": ["Clark"],
  "Henderson|Nevada": ["Clark"],
  "North Las Vegas|Nevada": ["Clark"],
  "Reno|Nevada": ["Washoe"],
  "Sparks|Nevada": ["Washoe"],
  "Manchester|New Hampshire": ["Hillsborough", "Merrimack", "Rockingham"],
  "Nashua|New Hampshire": ["Hillsborough"],
  "Concord|New Hampshire": ["Merrimack"],
  "Dover|New Hampshire": ["Strafford", "Rockingham"],
  "Rochester|New Hampshire": ["Strafford"],
  "Newark|New Jersey": ["Essex", "Hudson", "Union"],
  "Jersey City|New Jersey": ["Hudson", "Essex"],
  "Paterson|New Jersey": ["Passaic", "Bergen"],
  "Elizabeth|New Jersey": ["Union", "Essex"],
  "Lakewood|New Jersey": ["Ocean", "Monmouth"],
  "Albuquerque|New Mexico": ["Bernalillo", "Sandoval", "Valencia"],
  "Las Cruces|New Mexico": ["Doña Ana"],
  "Rio Rancho|New Mexico": ["Sandoval", "Bernalillo"],
  "Santa Fe|New Mexico": ["Santa Fe"],
  "Roswell|New Mexico": ["Chaves"],
  "New York|New York": ["New York", "Kings", "Queens", "Bronx", "Richmond"],
  "Buffalo|New York": ["Erie", "Niagara"],
  "Rochester|New York": ["Monroe"],
  "Yonkers|New York": ["Westchester", "Bronx"],
  "Syracuse|New York": ["Onondaga"],
  "Charlotte|North Carolina": ["Mecklenburg", "Union", "Cabarrus", "Gaston"],
  "Raleigh|North Carolina": ["Wake", "Durham", "Johnston"],
  "Greensboro|North Carolina": ["Guilford"],
  "Durham|North Carolina": ["Durham", "Wake", "Orange"],
  "Winston-Salem|North Carolina": ["Forsyth", "Davidson"],
  "Fargo|North Dakota": ["Cass"],
  "Bismarck|North Dakota": ["Burleigh", "Morton"],
  "Grand Forks|North Dakota": ["Grand Forks"],
  "Minot|North Dakota": ["Ward"],
  "West Fargo|North Dakota": ["Cass"],
  "Columbus|Ohio": ["Franklin", "Delaware", "Fairfield"],
  "Cleveland|Ohio": ["Cuyahoga", "Lake", "Lorain"],
  "Cincinnati|Ohio": ["Hamilton", "Butler", "Clermont"],
  "Toledo|Ohio": ["Lucas", "Wood"],
  "Akron|Ohio": ["Summit", "Portage"],
  "Oklahoma City|Oklahoma": ["Oklahoma", "Cleveland", "Canadian"],
  "Tulsa|Oklahoma": ["Tulsa", "Wagoner", "Rogers"],
  "Norman|Oklahoma": ["Cleveland", "McClain"],
  "Broken Arrow|Oklahoma": ["Tulsa", "Wagoner"],
  "Edmond|Oklahoma": ["Oklahoma", "Logan"],
  "Portland|Oregon": ["Multnomah", "Washington", "Clackamas"],
  "Salem|Oregon": ["Marion", "Polk"],
  "Eugene|Oregon": ["Lane"],
  "Gresham|Oregon": ["Multnomah", "Clackamas"],
  "Hillsboro|Oregon": ["Washington", "Multnomah"],
  "Philadelphia|Pennsylvania": ["Philadelphia", "Montgomery", "Delaware", "Bucks"],
  "Pittsburgh|Pennsylvania": ["Allegheny", "Westmoreland", "Washington"],
  "Allentown|Pennsylvania": ["Lehigh", "Northampton"],
  "Reading|Pennsylvania": ["Berks"],
  "Erie|Pennsylvania": ["Erie"],
  "Providence|Rhode Island": ["Providence", "Kent"],
  "Warwick|Rhode Island": ["Kent", "Providence"],
  "Cranston|Rhode Island": ["Providence", "Kent"],
  "Pawtucket|Rhode Island": ["Providence"],
  "East Providence|Rhode Island": ["Providence"],
  "Charleston|South Carolina": ["Charleston", "Berkeley", "Dorchester"],
  "Columbia|South Carolina": ["Richland", "Lexington"],
  "North Charleston|South Carolina": ["Charleston", "Berkeley", "Dorchester"],
  "Mount Pleasant|South Carolina": ["Charleston", "Berkeley"],
  "Rock Hill|South Carolina": ["York", "Lancaster"],
  "Sioux Falls|South Dakota": ["Minnehaha", "Lincoln"],
  "Rapid City|South Dakota": ["Pennington", "Meade"],
  "Aberdeen|South Dakota": ["Brown"],
  "Brookings|South Dakota": ["Brookings"],
  "Watertown|South Dakota": ["Codington"],
  "Nashville|Tennessee": ["Davidson", "Williamson", "Rutherford", "Sumner"],
  "Memphis|Tennessee": ["Shelby", "Fayette"],
  "Knoxville|Tennessee": ["Knox", "Blount", "Anderson"],
  "Chattanooga|Tennessee": ["Hamilton"],
  "Clarksville|Tennessee": ["Montgomery"],
  "Houston|Texas": ["Harris", "Fort Bend", "Montgomery", "Brazoria"],
  "San Antonio|Texas": ["Bexar", "Comal", "Guadalupe"],
  "Dallas|Texas": ["Dallas", "Collin", "Denton", "Tarrant"],
  "Austin|Texas": ["Travis", "Williamson", "Hays"],
  "Fort Worth|Texas": ["Tarrant", "Denton", "Parker"],
  "Salt Lake City|Utah": ["Salt Lake", "Davis", "Utah"],
  "West Valley City|Utah": ["Salt Lake"],
  "West Jordan|Utah": ["Salt Lake"],
  "Provo|Utah": ["Utah"],
  "Orem|Utah": ["Utah"],
  "Burlington|Vermont": ["Chittenden"],
  "South Burlington|Vermont": ["Chittenden"],
  "Rutland|Vermont": ["Rutland"],
  "Essex Junction|Vermont": ["Chittenden"],
  "Barre|Vermont": ["Washington"],
  "Virginia Beach|Virginia": ["Virginia Beach", "Chesapeake"],
  "Chesapeake|Virginia": ["Chesapeake", "Virginia Beach", "Suffolk"],
  "Norfolk|Virginia": ["Norfolk", "Virginia Beach"],
  "Richmond|Virginia": ["Richmond", "Henrico", "Chesterfield"],
  "Newport News|Virginia": ["Newport News", "Hampton", "York"],
  "Seattle|Washington": ["King", "Snohomish", "Pierce"],
  "Spokane|Washington": ["Spokane"],
  "Tacoma|Washington": ["Pierce", "King"],
  "Vancouver|Washington": ["Clark"],
  "Bellevue|Washington": ["King"],
  "Charleston|West Virginia": ["Kanawha", "Putnam"],
  "Huntington|West Virginia": ["Cabell", "Wayne"],
  "Morgantown|West Virginia": ["Monongalia"],
  "Parkersburg|West Virginia": ["Wood"],
  "Wheeling|West Virginia": ["Ohio", "Marshall"],
  "Milwaukee|Wisconsin": ["Milwaukee", "Waukesha", "Ozaukee"],
  "Madison|Wisconsin": ["Dane"],
  "Green Bay|Wisconsin": ["Brown"],
  "Kenosha|Wisconsin": ["Kenosha", "Racine"],
  "Racine|Wisconsin": ["Racine", "Kenosha"],
  "Cheyenne|Wyoming": ["Laramie"],
  "Casper|Wyoming": ["Natrona"],
  "Gillette|Wyoming": ["Campbell"],
  "Laramie|Wyoming": ["Albany"],
  "Rock Springs|Wyoming": ["Sweetwater"],
};

export function nearbyCounties(city: string, state: string): string[] {
  return NEARBY[`${city}|${state}`] ?? [];
}
