/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as SuitabilityRouteImport } from './routes/suitability'
import { Route as SlugCodeRouteImport } from './routes/$slug.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitabilityRoute = SuitabilityRouteImport.update({
  id: '/suitability',
  path: '/suitability',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCodeRoute = SlugCodeRouteImport.update({
  id: '/$slug/$code',
  path: '/$slug/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/copyright': typeof CopyrightRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/copyright' | '/suitability' | '/$slug/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/copyright' | '/suitability' | '/$slug/$code'
  id:
    '__root__' | '/' | '/about' | '/copyright' | '/suitability' | '/$slug/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CopyrightRoute: typeof CopyrightRoute
  SuitabilityRoute: typeof SuitabilityRoute
  SlugCodeRoute: typeof SlugCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suitability': {
      id: '/suitability'
      path: '/suitability'
      fullPath: '/suitability'
      preLoaderRoute: typeof SuitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/$code': {
      id: '/$slug/$code'
      path: '/$slug/$code'
      fullPath: '/$slug/$code'
      preLoaderRoute: typeof SlugCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CopyrightRoute: CopyrightRoute,
  SuitabilityRoute: SuitabilityRoute,
  SlugCodeRoute: SlugCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
