/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommissionCalculatorRouteImport } from './routes/commission-calculator'
import { Route as CommunicationRouteImport } from './routes/communication'
import { Route as CopyrightRouteImport } from './routes/copyright'
import { Route as FacebookAdsRouteImport } from './routes/facebook-ads'
import { Route as PaymentSelectionRouteImport } from './routes/payment-selection'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as StartRouteImport } from './routes/start'
import { Route as SubscribeNowRouteImport } from './routes/subscribe-now'
import { Route as SuitabilityRouteImport } from './routes/suitability'
import { Route as SlugCodeRouteImport } from './routes/$slug.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionCalculatorRoute = CommissionCalculatorRouteImport.update({
  id: '/commission-calculator',
  path: '/commission-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationRoute = CommunicationRouteImport.update({
  id: '/communication',
  path: '/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightRoute = CopyrightRouteImport.update({
  id: '/copyright',
  path: '/copyright',
  getParentRoute: () => rootRouteImport,
} as any)
const FacebookAdsRoute = FacebookAdsRouteImport.update({
  id: '/facebook-ads',
  path: '/facebook-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSelectionRoute = PaymentSelectionRouteImport.update({
  id: '/payment-selection',
  path: '/payment-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeNowRoute = SubscribeNowRouteImport.update({
  id: '/subscribe-now',
  path: '/subscribe-now',
  getParentRoute: () => rootRouteImport,
} as any)
const SuitabilityRoute = SuitabilityRouteImport.update({
  id: '/suitability',
  path: '/suitability',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugCodeRoute = SlugCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/about': typeof AboutRoute
  '/commission-calculator': typeof CommissionCalculatorRoute
  '/communication': typeof CommunicationRoute
  '/copyright': typeof CopyrightRoute
  '/facebook-ads': typeof FacebookAdsRoute
  '/payment-selection': typeof PaymentSelectionRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/subscribe-now': typeof SubscribeNowRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/about': typeof AboutRoute
  '/commission-calculator': typeof CommissionCalculatorRoute
  '/communication': typeof CommunicationRoute
  '/copyright': typeof CopyrightRoute
  '/facebook-ads': typeof FacebookAdsRoute
  '/payment-selection': typeof PaymentSelectionRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/subscribe-now': typeof SubscribeNowRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/about': typeof AboutRoute
  '/commission-calculator': typeof CommissionCalculatorRoute
  '/communication': typeof CommunicationRoute
  '/copyright': typeof CopyrightRoute
  '/facebook-ads': typeof FacebookAdsRoute
  '/payment-selection': typeof PaymentSelectionRoute
  '/sources': typeof SourcesRoute
  '/start': typeof StartRoute
  '/subscribe-now': typeof SubscribeNowRoute
  '/suitability': typeof SuitabilityRoute
  '/$slug/$code': typeof SlugCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about'
    | '/commission-calculator'
    | '/communication'
    | '/copyright'
    | '/facebook-ads'
    | '/payment-selection'
    | '/sources'
    | '/start'
    | '/subscribe-now'
    | '/suitability'
    | '/$slug/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about'
    | '/commission-calculator'
    | '/communication'
    | '/copyright'
    | '/facebook-ads'
    | '/payment-selection'
    | '/sources'
    | '/start'
    | '/subscribe-now'
    | '/suitability'
    | '/$slug/$code'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about'
    | '/commission-calculator'
    | '/communication'
    | '/copyright'
    | '/facebook-ads'
    | '/payment-selection'
    | '/sources'
    | '/start'
    | '/subscribe-now'
    | '/suitability'
    | '/$slug/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  AboutRoute: typeof AboutRoute
  CommissionCalculatorRoute: typeof CommissionCalculatorRoute
  CommunicationRoute: typeof CommunicationRoute
  CopyrightRoute: typeof CopyrightRoute
  FacebookAdsRoute: typeof FacebookAdsRoute
  PaymentSelectionRoute: typeof PaymentSelectionRoute
  SourcesRoute: typeof SourcesRoute
  StartRoute: typeof StartRoute
  SubscribeNowRoute: typeof SubscribeNowRoute
  SuitabilityRoute: typeof SuitabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission-calculator': {
      id: '/commission-calculator'
      path: '/commission-calculator'
      fullPath: '/commission-calculator'
      preLoaderRoute: typeof CommissionCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication': {
      id: '/communication'
      path: '/communication'
      fullPath: '/communication'
      preLoaderRoute: typeof CommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright': {
      id: '/copyright'
      path: '/copyright'
      fullPath: '/copyright'
      preLoaderRoute: typeof CopyrightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facebook-ads': {
      id: '/facebook-ads'
      path: '/facebook-ads'
      fullPath: '/facebook-ads'
      preLoaderRoute: typeof FacebookAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-selection': {
      id: '/payment-selection'
      path: '/payment-selection'
      fullPath: '/payment-selection'
      preLoaderRoute: typeof PaymentSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe-now': {
      id: '/subscribe-now'
      path: '/subscribe-now'
      fullPath: '/subscribe-now'
      preLoaderRoute: typeof SubscribeNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suitability': {
      id: '/suitability'
      path: '/suitability'
      fullPath: '/suitability'
      preLoaderRoute: typeof SuitabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/$code': {
      id: '/$slug/$code'
      path: '/$code'
      fullPath: '/$slug/$code'
      preLoaderRoute: typeof SlugCodeRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugCodeRoute: typeof SlugCodeRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugCodeRoute: SlugCodeRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  AboutRoute: AboutRoute,
  CommissionCalculatorRoute: CommissionCalculatorRoute,
  CommunicationRoute: CommunicationRoute,
  CopyrightRoute: CopyrightRoute,
  FacebookAdsRoute: FacebookAdsRoute,
  PaymentSelectionRoute: PaymentSelectionRoute,
  SourcesRoute: SourcesRoute,
  StartRoute: StartRoute,
  SubscribeNowRoute: SubscribeNowRoute,
  SuitabilityRoute: SuitabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
